name: my_flutter_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  flutter_keyboard_visibility: ^6.0.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.5
  shared_preferences: ^2.5.2
  font_awesome_flutter: ^10.8.0
  slide_to_act: any
  intl: ^0.20.2
  location: ^8.0.0
  geocoding: ^3.0.0
  firebase_storage: ^12.4.4
  image_picker: ^1.1.2
  mobile_scanner: ^6.0.7
  firebase_auth: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat/static/Montserrat-Bold.ttf
          weight: 700

  assets:
    - assets/images/logo.jpg
